services:
  mcpo:
    hostname: mcpo
    networks:
      - traefik
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./mcpo:/mcpo

networks:
  traefik:
    external: true
